//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \k0-X\Backups\.
        /// </summary>
        public static string Backups {
            get {
                return ResourceManager.GetString("Backups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \k0-X\EffTran\.
        /// </summary>
        public static string EffTranFolder {
            get {
                return ResourceManager.GetString("EffTranFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \k0-X\EffTran\Material\.
        /// </summary>
        public static string EffTranMaterialsFolder {
            get {
                return ResourceManager.GetString("EffTranMaterialsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the k0X Database connection.\nThe Server might be down, not installed, misconfigured or just offline.\nRight click the notifier --&gt; Databases\n\nError message:\n\n.
        /// </summary>
        public static string Error404 {
            get {
                return ResourceManager.GetString("Error404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when connecting to the k0X Database.
        /// </summary>
        public static string Error404Header {
            get {
                return ResourceManager.GetString("Error404Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \k0-X\Exceptions\.
        /// </summary>
        public static string Exceptions {
            get {
                return ResourceManager.GetString("Exceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Features.txt.
        /// </summary>
        public static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \k0-X\.
        /// </summary>
        public static string k0XFolder {
            get {
                return ResourceManager.GetString("k0XFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \k0-X\Backups\LIMS.xml.
        /// </summary>
        public static string Linaa {
            get {
                return ResourceManager.GetString("Linaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \k0-X\Backups\LIMS.Changes.xml.
        /// </summary>
        public static string LinaaChanges {
            get {
                return ResourceManager.GetString("LinaaChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \k0-X\MatSSF\.
        /// </summary>
        public static string MatSSFFolder {
            get {
                return ResourceManager.GetString("MatSSFFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mcnpx.exe.
        /// </summary>
        public static string MCNPXExe {
            get {
                return ResourceManager.GetString("MCNPXExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c:\mcnpx\.
        /// </summary>
        public static string MCNPXFolder {
            get {
                return ResourceManager.GetString("MCNPXFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \k0-X\Preferences.xml.
        /// </summary>
        public static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Preferences.xml.
        /// </summary>
        public static string PreferencesDev {
            get {
                return ResourceManager.GetString("PreferencesDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\private$\k0X.Acquisitions.
        /// </summary>
        public static string QMAcquisitions {
            get {
                return ResourceManager.GetString("QMAcquisitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\private$\k0X.Backups.
        /// </summary>
        public static string QMBackups {
            get {
                return ResourceManager.GetString("QMBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\private$\k0X.Exceptions.
        /// </summary>
        public static string QMExceptions {
            get {
                return ResourceManager.GetString("QMExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\private$\k0X.Works.
        /// </summary>
        public static string QMWorks {
            get {
                return ResourceManager.GetString("QMWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Overrider.
        /// </summary>
        public static string ResourcesOverrider {
            get {
                return ResourceManager.GetString("ResourcesOverrider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \k0XResources\.
        /// </summary>
        public static string ResourcesPath {
            get {
                return ResourceManager.GetString("ResourcesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Restarting.
        /// </summary>
        public static string Restarting {
            get {
                return ResourceManager.GetString("Restarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \k0-X\SolCoi\.
        /// </summary>
        public static string SolCoiFolder {
            get {
                return ResourceManager.GetString("SolCoiFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \k0-X\WCalc.htm.
        /// </summary>
        public static string WCalc {
            get {
                return ResourceManager.GetString("WCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \k0-X\XCOMEnergies.txt.
        /// </summary>
        public static string XCOMEnergies {
            get {
                return ResourceManager.GetString("XCOMEnergies", resourceCulture);
            }
        }
    }
}
