//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Atom {
            get {
                object obj = ResourceManager.GetObject("Atom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backups\.
        /// </summary>
        public static string Backups {
            get {
                return ResourceManager.GetString("Backups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Bomb {
            get {
                object obj = ResourceManager.GetObject("Bomb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Browse {
            get {
                object obj = ResourceManager.GetObject("Browse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Clean {
            get {
                object obj = ResourceManager.GetObject("Clean", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to curves.
        /// </summary>
        public static string CurvesResource {
            get {
                return ResourceManager.GetString("CurvesResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \DevFiles\.
        /// </summary>
        public static string DevFiles {
            get {
                return ResourceManager.GetString("DevFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EffTran\.
        /// </summary>
        public static string EffTranFolder {
            get {
                return ResourceManager.GetString("EffTranFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EffTran\Material\.
        /// </summary>
        public static string EffTranMaterialsFolder {
            get {
                return ResourceManager.GetString("EffTranMaterialsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceptions\.
        /// </summary>
        public static string Exceptions {
            get {
                return ResourceManager.GetString("Exceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.txt.
        /// </summary>
        public static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Geometries {
            get {
                object obj = ResourceManager.GetObject("Geometries", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Geometry {
            get {
                object obj = ResourceManager.GetObject("Geometry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Green {
            get {
                object obj = ResourceManager.GetObject("Green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Handpoint {
            get {
                object obj = ResourceManager.GetObject("Handpoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \k0-X\.
        /// </summary>
        public static string k0XFolder {
            get {
                return ResourceManager.GetString("k0XFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIMS.xml.
        /// </summary>
        public static string Linaa {
            get {
                return ResourceManager.GetString("Linaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backups\LIMS.Changes.xml.
        /// </summary>
        public static string LinaaChanges {
            get {
                return ResourceManager.GetString("LinaaChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LogoMenu {
            get {
                object obj = ResourceManager.GetObject("LogoMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Matrices {
            get {
                object obj = ResourceManager.GetObject("Matrices", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrices.xml.
        /// </summary>
        public static string MatricesFile {
            get {
                return ResourceManager.GetString("MatricesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mcnpx.exe.
        /// </summary>
        public static string MCNPXExe {
            get {
                return ResourceManager.GetString("MCNPXExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a:\mcnpx\.
        /// </summary>
        public static string MCNPXFolder {
            get {
                return ResourceManager.GetString("MCNPXFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Monitors {
            get {
                object obj = ResourceManager.GetObject("Monitors", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Project {
            get {
                object obj = ResourceManager.GetObject("Project", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Radioactive {
            get {
                object obj = ResourceManager.GetObject("Radioactive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Reaction {
            get {
                object obj = ResourceManager.GetObject("Reaction", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Reactor {
            get {
                object obj = ResourceManager.GetObject("Reactor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Reactors {
            get {
                object obj = ResourceManager.GetObject("Reactors", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Red {
            get {
                object obj = ResourceManager.GetObject("Red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RefMat1 {
            get {
                object obj = ResourceManager.GetObject("RefMat1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overrider.
        /// </summary>
        public static string ResourcesOverrider {
            get {
                return ResourceManager.GetString("ResourcesOverrider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting.
        /// </summary>
        public static string Restarting {
            get {
                return ResourceManager.GetString("Restarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soleffi\.
        /// </summary>
        public static string SolCoiFolder {
            get {
                return ResourceManager.GetString("SolCoiFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to solcoi.
        /// </summary>
        public static string SolCoiResource {
            get {
                return ResourceManager.GetString("SolCoiResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Springfield {
            get {
                object obj = ResourceManager.GetObject("Springfield", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSF\.
        /// </summary>
        public static string SSFFolder {
            get {
                return ResourceManager.GetString("SSFFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSFPreferences.
        /// </summary>
        public static string SSFPreferences {
            get {
                return ResourceManager.GetString("SSFPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatSSF.
        /// </summary>
        public static string SSFResource {
            get {
                return ResourceManager.GetString("SSFResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Standards {
            get {
                object obj = ResourceManager.GetObject("Standards", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SubSamples {
            get {
                object obj = ResourceManager.GetObject("SubSamples", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Vials {
            get {
                object obj = ResourceManager.GetObject("Vials", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Worker2 {
            get {
                object obj = ResourceManager.GetObject("Worker2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.004
        ///0.005
        ///0.006
        ///0.008
        ///0.01
        ///0.015
        ///0.02
        ///0.03
        ///0.04
        ///0.05
        ///0.06
        ///0.08
        ///0.1
        ///0.15
        ///0.2
        ///0.3
        ///0.4
        ///0.5
        ///0.6
        ///0.8
        ///1
        ///1.022
        ///1.25
        ///1.5
        ///2
        ///2.044
        ///3.
        /// </summary>
        public static string XCOM {
            get {
                return ResourceManager.GetString("XCOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uFinder\.
        /// </summary>
        public static string XCOMFolder {
            get {
                return ResourceManager.GetString("XCOMFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uFinderPreferences.
        /// </summary>
        public static string XCOMPreferences {
            get {
                return ResourceManager.GetString("XCOMPreferences", resourceCulture);
            }
        }
    }
}
